version: '3.8'

services:
  go-parser:
    build: ./go-parser
    container_name: go-parser-server
    ports:
      - "8080:8080"

  goats:
    build: .
    container_name: goats
    ports:
      - "8000:8000"
    depends_on:
      - go-parser
